#coding=UTF8
set completion=ignore-case on
alias src='source ~/.bashrc'
alias g='gvim'
alias status='git status'
alias push='git push origin master'
alias pull='git pull origin master'
alias add='git add *'
alias commit='git commit -m'
alias ll='ls -l'
