#coding=UTF8
set completion=ignore-case on
alias src='source ~/.bashrc'
alias g='gvim'
alias status='git status'
alias push='git push'
alias pull='git pull'
alias add='git add *'
alias commit='git commit'
alias ll='ls -l'
